Geocoded <- read_excel("Documents/Polimi/Non Parametric/Geocoded.xlsx")

Geocoded$suburb <- str_replace(Geocoded$suburb, "Potrero Terrace", "Potrero Hill")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Hunters Point", "Bayview Hunters Point")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Bayview", "Bayview Hunters Point")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Bayview Hunters Point District", "Bayview Hunters Point")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Bayview Hunters Point Heights", "Bayview Hunters Point")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Bayview Hunters Point Hunters Point", "Bayview Hunters Point")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Upper Market", "Castro/Upper Market")
Geocoded$suburb <- str_replace(Geocoded$suburb, "The Castro", "Castro/Upper Market")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Castro District", "Castro/Upper Market")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Financial District", "Financial District/South Beach")
Geocoded$suburb <- str_replace(Geocoded$suburb, "South Beach", "Financial District/South Beach")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Financial District/Financial District/South Beach", "Financial District/South Beach")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Lower Haight", "Haight Ashbury")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Haight-Ashbury", "Haight Ashbury")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Lake", "Outer Richmond")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Outer Richmond Shore", "Lakeshore")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Lone Mountain", "Lone Mountain/USF")
Geocoded$suburb <- str_replace(Geocoded$suburb, "University Mound", "Excelsior")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Marina District", "Marina")
Geocoded$suburb <- str_replace(Geocoded$suburb, "McLaren Park Community Garden", "McLaren Park")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Ingleside", "Oceanview/Merced/Ingleside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Oceanview/Merced/Ingleside Terrace", "Oceanview/Merced/Ingleside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Ocean View", "Oceanview/Merced/Ingleside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Merced Manor", "Oceanview/Merced/Ingleside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Presidio Terrace", "Presidio")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Parkside", "Sunset/Parkside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Sunset District", "Sunset/Parkside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Saint Francis Wood", "West of Twin Peaks")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Forest Hill", "West of Twin Peaks")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Mission District", "Mission")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Mission Dolores", "Mission")
#Geocoded$suburb <- str_replace(Geocoded$suburb, "Richmond District", "Inner Richmond")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Lower Nob Hill", "Nob Hill")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Lower Pacific Heights", "Pacific Heights")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Alamo Square", "Western Addition")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Anza Vista", "Western Addition")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Cathedral Hill", "Western Addition")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Cole Valley", "Haight Ashbury")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Jordan Park", "Inner Richmond")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Lower Nob Hill", "Nob Hill")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Cayuga Terrace", "Outer Mission")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Mission Terrace", "Outer Mission")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Sunnyside", "Outer Mission")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Golden Gate Heights", "Inner Sunset")
Geocoded$suburb <- str_replace(Geocoded$suburb, "North Panhandle", "Western Addition")
Geocoded$suburb <- str_replace(Geocoded$suburb, "North of Panhandle", "Western Addition")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Outer Sunset", "Sunset/Parkside")
Geocoded$suburb <- str_replace(Geocoded$suburb, "West SoMa", "South of Market")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Duboce Triangle", "Castro/Upper market")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Cow Hollow", "Marina")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Union Street", "Marina")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Transbay", "Financial District/South Beach")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Telegraph Hill", "North Beach")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Sutro Heights", "Outer Richmond")
Geocoded$suburb <- str_replace(Geocoded$suburb, "St. Mary's Park", "Bernal Heights")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Silver Terrace", "Bayview Hunters Point")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Russian Hill-Macondray Lane Historic District", "Russian Hill")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Rincon Hill", "Financial District/South Beach")
Geocoded$suburb[Geocoded$suburb == "Richmond District" & Geocoded$postcode %like% "94121"] <- "Outer Richmond"
Geocoded$suburb[Geocoded$suburb == "Richmond District" & Geocoded$postcode %like% "94118"] <- "Inner Richmond"
Geocoded$suburb <- str_replace(Geocoded$suburb, "Peralta Heights", "Bernal Heights")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Northeast Waterfront Historic District", "North Beach")
Geocoded$suburb <- str_replace(Geocoded$suburb, "Mount Davidson Manor", "West of Twin Peaks")


Geocoded <- Geocoded[!duplicated(Geocoded),]
New_construction_clean <- merge(New_construction_clean,subset(Geocoded, select=c("original_address", "lat", "lon")), by.x="address", by.y="original_address")
write.csv(New_construction_clean,"/Users/saratonazzi/Documents/Polimi/Non Parametric/New_construction_clean_geocoded.csv", row.names = FALSE)
